version: '3.9'
services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        restart: on-failure:5
        env_file:
            - ./.env
    mongo_dump:
        build: ./db/dump
        env_file:
            - ./.env
    node:
        build: .
        ports:
            - '8080:8080'
        restart: on-failure:5
        depends_on:
            - mongo
